import Head from "next/head";
import Link from "next/link";
import Header from "./components/Header";
import Styles from "../styles/Earphone.module.css";
import Footer from "./components/Footer";
import React from "react";

const Earphone: React.FC = () => {
  return (
    <>
      <Head>
        <title>Audiophile | Earphones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div id={Styles.earphone}>
        <div>
          <Header />
          <nav>
            <h1>EARPHONES</h1>
          </nav>
        </div>

        <section>
          <aside>
            <img src="/Group.png" alt="earphone" />
            <nav>
              <span>NEW PRODUCT</span>
              <h1>YX1 WIRELESS</h1>
              <h1>EARPHONES</h1>
              <p>
                Tailor your listening experience with bespoke dynamic drivers
                from the new YX1 Wireless Earphones. Enjoy incredible
                high-fidelity sound even in noisy environments with its active
                noise cancellation feature.
              </p>
              <Link href="/product/yx1-earphones">
                <button>SEE PRODUCT</button>
              </Link>
            </nav>
          </aside>
        </section>

        <summary>
          <div>
            <img src="/headphone.png" alt="headphone" />
            <h4>HEADPHONES</h4>
            <p>
              SHOP <img src="/arrow.png" alt="arrow" />
            </p>
          </div>

          <div>
            <img src="/speaker.png" alt="speaker" />
            <h4>SPEAKERS</h4>
            <p>
              SHOP <img src="/arrow.png" alt="arrow" />
            </p>
          </div>

          <div>
            <img src="/earphone.png" alt="earphone" />
            <h4>EARPHONES</h4>
            <p>
              SHOP <img src="/arrow.png" alt="arrow" />
            </p>
          </div>
        </summary>

        <Footer />
      </div>
    </>
  );
};

export default Earphone;
