import Head from "next/head";
import Link from "next/link";
import Header from "./components/Header";
import Styles from "../styles/Headphone.module.css";
import Footer from "./components/Footer.tsx";
import React from "react";

const Headphone: React.FC = () => {
  return (
    <>
      <Head>
        <title>Audiophile | Headphone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div id={Styles.headerphone}>
        <div>
          <Header />
          <nav>
            <h1>HEADPHONES</h1>
          </nav>
        </div>

        <section>
          <aside>
            <img src="/darkhead.png" alt="headphone" />
            <nav>
              <span>NEW PRODUCT</span>
              <h1>XX99 Mark II</h1>
              <h1>Headphones</h1>
              <p>
                The new XX99 Mark II headphones is the pinnacle of pristine
                audio. It redefines your premium headphone experience by
                reproducing the balanced depth and precision of studio-quality
                sound.
              </p>
              <Link href="/product/xx99-mark-two">
                <button>SEE PRODUCT</button>
              </Link>
            </nav>
          </aside>

          <aside>
            <nav>
              <h1>XX99 Mark I</h1>
              <h1>Headphones</h1>
              <p>
                As the gold standard for headphones, the classic XX99 Mark I
                offers detailed and accurate audio reproduction for audiophiles,
                mixing engineers, and music aficionados alike in studios and on
                the go.
              </p>
              <Link href="/product/xx99-mark-one">
                <button>SEE PRODUCT</button>
              </Link>
            </nav>
            <img src="/head.png" alt="headphone" />
          </aside>

          <aside>
            <img src="/whitehead.png" alt="headphone" />
            <nav>
              <h1>XX59</h1>
              <h1>Headphones</h1>
              <p>
                Enjoy your audio almost anywhere and customize it to your
                specific tastes with the XX59 headphones. The stylish yet durable
                versatile wireless headset is a brilliant companion at home or
                on the move.
              </p>
              <Link href="/product/xx59-headphone">
                <button>SEE PRODUCT</button>
              </Link>
            </nav>
          </aside>
        </section>

        <summary>
          <div>
            <img src="/headphone.png" alt="headphone" />
            <h4>HEADPHONES</h4>
            <p>
              SHOP <img src="/arrow.png" alt="arrow" />
            </p>
          </div>
          <div>
            <img src="/speaker.png" alt="speaker" />
            <h4>SPEAKERS</h4>
            <p>
              SHOP <img src="/arrow.png" alt="arrow" />
            </p>
          </div>
          <div>
            <img src="/earphone.png" alt="earphone" />
            <h4>EARPHONES</h4>
            <p>
              SHOP <img src="/arrow.png" alt="arrow" />
            </p>
          </div>
        </summary>

        <Footer />
      </div>
    </>
  );
};

export default Headphone;
