import Head from "next/head";
import Link from "next/link";
import Header from "./components/Header";
import Styles from "../styles/Home.module.css";
import Footer from "./components/Footer";
import React from "react";

const Homepage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div id={Styles.home}>
        <div>
          <Header />

          <section>
            <span>NEW PRODUCT</span>
            <h1>XX99 Mark II</h1>
            <h1>Headphones</h1>
            <p>
              Experience natural, lifelike audio and exceptional build quality
              made for the passionate music enthusiast.
            </p>
            <Link href="/product/xx99-mark-two">
              <button>SEE PRODUCT</button>
            </Link>
          </section>
        </div>

        <section>
          <div>
            <img src="/headphone.png" alt="headphone" />
            <h4>HEADPHONES</h4>
            <Link href="/Headphone">
              <p>
                SHOP <img src="/arrow.png" alt="arrow" />
              </p>
            </Link>
          </div>

          <div>
            <img src="/speaker.png" alt="speaker" />
            <h4>SPEAKERS</h4>
            <Link href="/Speaker">
              <p>
                SHOP <img src="/arrow.png" alt="arrow" />
              </p>
            </Link>
          </div>

          <div>
            <img src="/earphone.png" alt="earphone" />
            <h4>EARPHONES</h4>
            <Link href="/Earphone">
              <p>
                SHOP <img src="/arrow.png" alt="arrow" />
              </p>
            </Link>
          </div>
        </section>

        <main>
          <section>
            <img src="/speaker.png" alt="speaker" />
            <nav>
              <h1>ZX9</h1>
              <h1>SPEAKER</h1>
              <p>
                Upgrade to premium speakers that are phenomenally built to
                deliver truly remarkable sound.
              </p>
              <Link href="/product/zx9-speaker">
                <button>SEE PRODUCT</button>
              </Link>
            </nav>
          </section>

          <aside>
            <h1>ZX7 SPEAKER</h1>
            <Link href="/product/zx7-speaker">
              <button>SEE PRODUCT</button>
            </Link>
          </aside>

          <summary>
            <section>
              <img src="/Bitmap-ear.png" alt="earphones" />
            </section>
            <section>
              <h1>YX1 EARPHONES</h1>
              <Link href="/product/yx1-earphones">
                <button>SEE PRODUCT</button>
              </Link>
            </section>
          </summary>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default Homepage;
