import Head from "next/head";
import React from "react";
import Homepage from "./Home";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <div>
        <Homepage />
      </div>
    </>
  );
};

export default Home;
