
import Head from "next/head";
import Link from "next/link";
import Header from "./components/Header";
import Styles from "../styles/Speaker.module.css";
import Footer from "./components/Footer";


export default function Speaker() {
  return (
    <>
      <Head>
        <title>Audiophile | Speaker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div id={Styles.speaker}>
        <div>
            <Header/>
            <nav>
                <h1>SPEAKERS</h1>
            </nav>
        </div>

        <section>
            <aside>
                <img src="/speaker2.png" alt="headphone" />
                <nav>
                    <span>NEW PRODUCT</span>
                    <h1>ZX9</h1>
                    <h1>SPEAKER</h1>
                    <p>Upgrade your sound system with the all new ZX9 active speaker. It’s a bookshelf speaker system that offers truly wireless connectivity -- creating new possibilities for more pleasing and practical audio setups.</p>
                    <Link href="/product/zx9-speaker">
                        <button>SEE PRODUCT</button>
                    </Link>
                    
                </nav>
            </aside>
            <aside>
                <nav>
                    <h1>ZX7</h1>
                    <h1>SPEAKER</h1>
                    <p>Stream high quality sound wirelessly with minimal loss. The ZX7 bookshelf speaker uses high-end audiophile components that represents the top of the line powered speakers for home or studio use.</p>
                    <Link href="/product/zx7-speaker">
                        <button>SEE PRODUCT</button>
                    </Link>
                </nav>
                <img src="/speaker1.png" alt="headphone" />
            </aside>
            
        </section>

        <summary>
            <div>
                <img src="/headphone.png" alt="headphone" />
                <h4>HEADPHONES</h4>
                <p>
                    SHOP 
                    <img src="/arrow.png" alt="" />
                </p>
            </div>
            <div>
                <img src="/speaker.png" alt="speaker" />
                <h4>SPEAKERS</h4>
                <p>
                    SHOP 
                    <img src="/arrow.png" alt="" />
                </p>
            </div>
            <div>
                <img src="/earphone.png" alt="earphone" />
                <h4>EARPHONES</h4>
                <p>
                    SHOP 
                    <img src="/arrow.png" alt="" />
                </p>
            </div>
        </summary>

        <Footer/>
      </div>
    </>
  );
}
